spring:
  jersey:
    application-path: /v1
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    password: password
    username: root
    url: jdbc:postgresql://localhost:5439/pscmsformdb


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: drop
      show-sql: true
    name: pscms-form-data-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/cop-local

  session:
    store-type: redis
    redis:
      namespace: spring:session:${spring.application.name}
      flush-mode: immediate
  redis:
    host: ${redis.host:redis.local.cop.homeoffice.gov.uk}
    port: ${redis.port:6379}
    password: ${redis.token:GswpoJO6fT3HXSP9tTOZ}
    ssl: ${redis.ssl:false}

server:
  servlet.context-path: /pscms-form-data-service
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  ssl:
    enabled: ${ssl.enabled:false}
    key-alias: cert
    key-store: /etc/keystore/keystore.p12
    key-store-password: changeit
    key-password: changeit
    key-store-type: PKCS12
    trust-store: ${javax.net.ssl.trustStore:/etc/keystore/cacerts}
    trust-store-password: ${javax.net.ssl.trustStorePassword:changeit}
    trust-store-type: ${javax.net.ssl.trustStoreType:PKCS12}
  port: ${server-port:8081}

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus, metrics,loggers"
